# Generated by Django 5.2.17 on 2026-09-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0004_unidad_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil', models.CharField(blank=True, max_length=20)),
                ('dominio', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('kilometros', models.PositiveIntegerField(blank=True, null=True)),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='unidades.unidad')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20)),
                ('observaciones', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('tipo_de_comprobante', models.CharField(choices=[('FACTURA', 'Factura'), ('REMITO', 'Remito'), ('SIN_COMPROBANTE', 'Sin comprobante'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_de_comprobante', models.CharField(blank=True, max_length=50)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ordenes_trabajo.ordentrabajo')),
            ],
        ),
    ]
