# Generated by Django 5.2.17 on 2026-09-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0001_initial'),
        ('unidades', '0004_unidad_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='alcance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.alcance'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidad_de_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidaddenegocio'),
        ),
    ]
