# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0002_ordentrabajo_alcance_ordentrabajo_unidad_de_negocio'),
        ('unidades', '0004_unidad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='alcance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.alcance'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='unidad_de_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.unidaddenegocio'),
        ),
    ]
