# Generated by Django 5.2.17 on 2026-09-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_alcance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_interno', models.AutoField(primary_key=True, serialize=False)),
                ('movil', models.CharField(blank=True, max_length=20, unique=True)),
                ('dominio', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('nro_chasis', models.CharField(blank=True, max_length=100)),
                ('nro_motor', models.CharField(blank=True, max_length=100)),
                ('capacidad_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad_tn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('alcance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.alcance')),
                ('unidad_de_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidaddenegocio')),
            ],
        ),
    ]
