# Generated by Django 5.2.17 on 2026-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
